from enum import StrEnum

class FlightStatus(StrEnum):
    ACTIVE = "ACTIVE"
    ENDED = "ENDED"

class Source(StrEnum):
    ATC = "ATC"
    READBACK = "READBACK"
    COCKPIT = "COCKPIT"

class ClearanceStatus(StrEnum):
    WAITING_READBACK = "WAITING_READBACK"
    WAITING_COCKPIT = "WAITING_COCKPIT"
    READBACK_ERROR = "READBACK_ERROR"
    SETTING_ERROR = "SETTING_ERROR"
    REVERIFYING = "REVERIFYING"
    VERIFIED = "VERIFIED"
    RESOLVED = "RESOLVED"

class EventType(StrEnum):
    FLIGHT_STARTED = "FLIGHT_STARTED"
    ATC_RECOGNIZED = "ATC_RECOGNIZED"
    READBACK_RECOGNIZED = "READBACK_RECOGNIZED"
    COCKPIT_RECOGNIZED = "COCKPIT_RECOGNIZED"
    READBACK_ERROR = "READBACK_ERROR"
    SETTING_ERROR = "SETTING_ERROR"
    ALERTED = "ALERTED"
    READBACK_UPDATED = "READBACK_UPDATED"
    COCKPIT_UPDATED = "COCKPIT_UPDATED"
    REVERIFYING = "REVERIFYING"
    VERIFIED = "VERIFIED"
    RESOLVED = "RESOLVED"
    FLIGHT_ENDED = "FLIGHT_ENDED"
